"use client";

import React, { useState, useEffect, useMemo, useRef } from "react";
import { motion, AnimatePresence } from "framer-motion";
import {
  FileText,
  Sparkles,
  Search,
  Download,
  Filter,
  Plus,
  Trash2,
  ChevronLeft,
  ChevronRight,
  Loader2,
  DollarSign,
  BarChart3,
  Calendar,
  AlertCircle,
  CheckCircle2,
  FileSpreadsheet,
  Printer,
} from "lucide-react";
import { PieChart, Pie, Cell, ResponsiveContainer, Tooltip, Legend } from "recharts";
import { Badge as HeroBadge } from "@heroui/react";
import { fetchSales, fetchDashboardStats, fetchReports, createReport, deleteReport } from "@/lib/api";
import { useActivityLog } from "@/lib/activityLog";

// ─── Demo / Real data toggle ─────────────────────────────────────────────────
// Set to `true` to show rich mock financial data in the sidebar chart.
// Set to `false` to show live data fetched from the backend API.
const DEMO_MODE = true;

const MOCK_FINANCIAL_DATA = {
  revenue:  148_720.50,
  expenses:  89_234.80,
};
// ─────────────────────────────────────────────────────────────────────────────

interface Report {
  id: number;
  name: string;
  summary: string;
  type: string;
  dateRange: string;
  formats: string;
  status: string;
  generatedBy: string;
  createdAt: string;
  lineItems?: ReportLineItem[];
  totalRevenue?: number;
  totalTransactions?: number;
}

interface ReportLineItem {
  label: string;
  qty: number;
  amount: number;
}


function getDateWindow(mode: string, customStart: string, customEnd: string): { start: string; end: string; label: string } {
  const now = new Date();

  if (mode === "today") {
    const d = now.toISOString().split("T")[0];
    return { start: `${d}T00:00:00`, end: `${d}T23:59:59`, label: "Today" };
  }

  if (mode === "this-week") {
    const day = now.getDay();
    const monday = new Date(now);
    monday.setDate(now.getDate() - ((day + 6) % 7));
    const start = monday.toISOString().split("T")[0];
    const end = now.toISOString().split("T")[0];
    return { start: `${start}T00:00:00`, end: `${end}T23:59:59`, label: "This Week" };
  }

  if (mode === "this-month") {
    const start = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}-01`;
    const end = now.toISOString().split("T")[0];
    return {
      start: `${start}T00:00:00`,
      end: `${end}T23:59:59`,
      label: `${now.toLocaleString("default", { month: "long" })} ${now.getFullYear()}`,
    };
  }

  if (mode === "this-year") {
    const start = `${now.getFullYear()}-01-01`;
    const end = now.toISOString().split("T")[0];
    return { start: `${start}T00:00:00`, end: `${end}T23:59:59`, label: `FY ${now.getFullYear()}` };
  }

  if (mode === "custom" && customStart && customEnd) {
    return {
      start: `${customStart}T00:00:00`,
      end: `${customEnd}T23:59:59`,
      label: `${customStart} → ${customEnd}`,
    };
  }

  // fallback: this month
  const start = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}-01`;
  const end = now.toISOString().split("T")[0];
  return { start: `${start}T00:00:00`, end: `${end}T23:59:59`, label: "This Month" };
}

function exportCSV(report: Report) {
  const csvContent = [
    ["INVENTORY MANAGEMENT SYSTEM", ""],
    ["AUDIT & TRANSACTION REPORT", ""],
    ["", ""],
    ["REPORT METADATA", ""],
    ["Report Name", report.name],
    ["Category", report.type],
    ["Reporting Period", report.dateRange],
    ["Generated By", report.generatedBy],
    ["Generated On", new Date(report.createdAt).toLocaleString()],
    ["Status", report.status],
    ["", ""],
    ["SUMMARY METRICS", ""],
    ["Total Revenue", `${(report.totalRevenue ?? 0).toFixed(2)} DH`],
    ["Total Transactions", String(report.totalTransactions ?? 0)],
    ["", ""],
    ["LINE ITEMS DETAILED BREAKDOWN", ""],
    ["Product Name", "Quantity Sold", "Revenue (DH)"]
  ];

  if (report.lineItems && report.lineItems.length > 0) {
    report.lineItems.forEach((item) => {
      csvContent.push([item.label, String(item.qty), item.amount.toFixed(2)]);
    });
  }

  // Format array to CSV string
  const csvString = csvContent
    .map(row => row.map(val => `"${val.replace(/"/g, '""')}"`).join(","))
    .join("\n");

  const blob = new Blob(["\uFEFF" + csvString], { type: "text/csv;charset=utf-8;" }); // include BOM for Excel UTF-8 compatibility
  const link = document.createElement("a");
  link.href = URL.createObjectURL(blob);
  link.download = `report_${report.name.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_${new Date().toISOString().split("T")[0]}.csv`;
  link.click();
}

function printReport(report: Report) {
  const items =
    report.lineItems && report.lineItems.length > 0
      ? report.lineItems
          .map(
            (item) =>
              `<tr><td style="padding:6px 8px;border-bottom:1px solid #eee;">${item.label}</td><td style="padding:6px 8px;border-bottom:1px solid #eee;text-align:center;">${item.qty}</td><td style="padding:6px 8px;border-bottom:1px solid #eee;text-align:right;">${item.amount.toFixed(2)} DH</td></tr>`
          )
          .join("")
      : `<tr><td colspan="3" style="padding:16px;text-align:center;color:#888;">No line items available</td></tr>`;

  const html = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>${report.name}</title>
      <style>
        body { font-family: -apple-system, sans-serif; margin: 40px; color: #1a1a1a; }
        h1 { font-size: 22px; font-weight: 900; margin-bottom: 4px; }
        .meta { color: #666; font-size: 12px; margin-bottom: 24px; }
        .summary { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; margin-bottom: 24px; }
        .summary-card { background: #f9f9f9; border-radius: 8px; padding: 16px; }
        .summary-card .value { font-size: 24px; font-weight: 900; }
        .summary-card .label { font-size: 11px; font-weight: 700; color: #888; text-transform: uppercase; letter-spacing: 0.08em; }
        table { width: 100%; border-collapse: collapse; }
        thead tr { background: #1a1a1a; color: white; font-size: 11px; text-transform: uppercase; }
        thead th { padding: 10px 8px; text-align: left; }
        @media print { body { margin: 20px; } }
      </style>
    </head>
    <body>
      <h1>${report.name}</h1>
      <div class="meta">Generated on ${new Date(report.createdAt).toLocaleString()} &nbsp;|&nbsp; Period: ${report.dateRange} &nbsp;|&nbsp; By: ${report.generatedBy}</div>
      <div class="summary">
        <div class="summary-card">
          <div class="value">${(report.totalRevenue ?? 0).toLocaleString("en-US", { minimumFractionDigits: 2 })} DH</div>
          <div class="label">Total Revenue</div>
        </div>
        <div class="summary-card">
          <div class="value">${report.totalTransactions ?? 0}</div>
          <div class="label">Total Transactions</div>
        </div>
      </div>
      <table>
        <thead><tr><th>Product</th><th>Qty Sold</th><th style="text-align:right;">Revenue</th></tr></thead>
        <tbody>${items}</tbody>
      </table>
    </body>
    </html>
  `;

  const win = window.open("", "_blank");
  if (!win) return;
  win.document.write(html);
  win.document.close();
  win.onload = () => { win.print(); };
}


export default function ReportsPage() {
  const { addLog } = useActivityLog();

  // Core report list
  const [reports, setReports] = useState<Report[]>([]);
  const [loading, setLoading] = useState(false);

  // Filter / generation controls
  const [dateMode, setDateMode] = useState<"today" | "this-week" | "this-month" | "this-year" | "custom">("this-month");
  const [customStart, setCustomStart] = useState("");
  const [customEnd, setCustomEnd] = useState("");
  const [reportType, setReportType] = useState<"Sales" | "Inventory" | "Financial">("Sales");

  // Table filters
  const [search, setSearch] = useState("");
  const [typeFilter, setTypeFilter] = useState<"all" | "Sales" | "Inventory" | "Financial">("all");

  // Pagination
  const [currentPage, setCurrentPage] = useState(1);
  const itemsPerPage = 5;

  // Toast
  const [toast, setToast] = useState<{ message: string; type: "success" | "error" | "info" } | null>(null);

  // Dashboard stats for the donut chart (real data)
  const [dashStats, setDashStats] = useState<{ revenue: number; expenses: number } | null>(null);

  const showToast = (message: string, type: "success" | "error" | "info" = "success") => {
    setToast({ message, type });
    setTimeout(() => setToast(null), 4000);
  };

  // Fetch dashboard stats for donut chart
  useEffect(() => {
    fetchDashboardStats()
      .then((data: any) => {
        if (data) {
          const revenue = Number(data.totalRevenue ?? data.revenue ?? 0);
          const expenses = Number(data.totalExpenses ?? data.expenses ?? revenue * 0.6);
          setDashStats({ revenue, expenses });
        }
      })
      .catch(() => {
        // Graceful fallback with placeholder
        setDashStats({ revenue: 0, expenses: 0 });
      });
  }, []);

  // Fetch reports from backend on mount
  useEffect(() => {
    setLoading(true);
    fetchReports()
      .then((data: any) => {
        if (data) {
          setReports(data);
        }
      })
      .catch((err: any) => {
        showToast(`Failed to load reports: ${err.message}`, "error");
      })
      .finally(() => {
        setLoading(false);
      });
  }, []);


  const handleGenerateReport = async () => {
    setLoading(true);
    try {
      const { start, end, label } = getDateWindow(dateMode, customStart, customEnd);
      const userName = typeof window !== "undefined" ? (sessionStorage.getItem("userName") || "System") : "System";

      // Fetch all sales in the window
      const salesData = await fetchSales({ start, end, size: 1000 });
      const sales: any[] = salesData?.content ?? [];

      // Aggregate line items by product name
      const productMap: Record<string, { qty: number; amount: number }> = {};
      let totalRevenue = 0;

      sales.forEach((sale: any) => {
        const saleTotal = Number(sale.totalAmount ?? 0);
        totalRevenue += saleTotal;
        (sale.items ?? []).forEach((item: any) => {
          const name: string = item.productName ?? item.name ?? "Unknown Product";
          const qty = Number(item.quantity ?? 1);
          const price = Number(item.unitPrice ?? item.price ?? 0);
          if (!productMap[name]) productMap[name] = { qty: 0, amount: 0 };
          productMap[name].qty += qty;
          productMap[name].amount += qty * price;
        });
      });

      const lineItems: ReportLineItem[] = Object.entries(productMap)
        .map(([label, v]) => ({ label, qty: v.qty, amount: v.amount }))
        .sort((a, b) => b.amount - a.amount)
        .slice(0, 50);

      const reportNames: Record<string, string> = {
        Sales: "Sales Summary Report",
        Inventory: "Inventory Status Report",
        Financial: "Financial Overview",
      };

      const newReport: Omit<Report, "id"> = {
        name: `${reportNames[reportType]} — ${label}`,
        summary: `${sales.length} transactions recorded in the selected period. Total revenue: ${totalRevenue.toLocaleString("en-US", { minimumFractionDigits: 2 })} DH.`,
        type: reportType,
        dateRange: label,
        formats: "PDF,CSV",
        status: "Ready",
        generatedBy: userName,
        createdAt: new Date().toISOString(),
        lineItems,
        totalRevenue,
        totalTransactions: sales.length,
      };

      const savedReport = await createReport(newReport);
      setReports((prev) => [savedReport, ...prev]);
      showToast(`✓ ${savedReport.name} generated — ${sales.length} transactions found`, "success");
      addLog(`Generated report: ${savedReport.name}`, "report");
    } catch (err: any) {
      showToast(`Failed to generate report: ${err.message || "Unknown error"}`, "error");
    } finally {
      setLoading(false);
    }
  };

  const handleDeleteReport = async (id: number, name: string) => {
    try {
      await deleteReport(id);
      setReports((prev) => prev.filter((r) => r.id !== id));
      showToast(`Report "${name}" deleted.`, "info");
      addLog(`Deleted report: ${name}`, "report");
    } catch (err: any) {
      showToast(`Failed to delete report: ${err.message || "Unknown error"}`, "error");
    }
  };

  const filteredReports = useMemo(() => {
    return reports.filter((r) => {
      const matchSearch =
        r.name.toLowerCase().includes(search.toLowerCase()) ||
        r.summary.toLowerCase().includes(search.toLowerCase());
      const matchType = typeFilter === "all" || r.type === typeFilter;
      return matchSearch && matchType;
    });
  }, [reports, search, typeFilter]);

  useEffect(() => { setCurrentPage(1); }, [search, typeFilter]);

  const totalPages = Math.max(1, Math.ceil(filteredReports.length / itemsPerPage));
  const paginatedReports = useMemo(() => {
    const start = (currentPage - 1) * itemsPerPage;
    return filteredReports.slice(start, start + itemsPerPage);
  }, [filteredReports, currentPage]);

  // Donut chart data — uses mock or real depending on DEMO_MODE
  const activeStats = DEMO_MODE ? MOCK_FINANCIAL_DATA : dashStats;

  const donutData = activeStats && (activeStats.revenue > 0 || activeStats.expenses > 0)
    ? [
        { name: "Revenue",  value: activeStats.revenue,  color: "#10B981" },
        { name: "Expenses", value: activeStats.expenses, color: "#F43F5E" },
      ]
    : [
        { name: "Revenue",  value: 1, color: "#10B981" },
        { name: "Expenses", value: 1, color: "#F43F5E" },
      ];

  const netProfit = activeStats ? Math.max(0, activeStats.revenue - activeStats.expenses) : 0;

  return (
    <div className="min-h-screen bg-[#f4f7fe] dark:bg-background px-4 md:px-8 py-8 text-foreground relative overflow-hidden">
      {/* Background glows */}
      <div className="absolute top-[-10%] left-[-10%] w-[35%] h-[35%] rounded-full bg-violet-500/5 blur-[120px] pointer-events-none" />
      <div className="absolute bottom-[-10%] right-[-10%] w-[35%] h-[35%] rounded-full bg-indigo-500/5 blur-[120px] pointer-events-none" />

      <div className="max-w-[1400px] mx-auto space-y-6 relative z-10">

        <header className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div>
            <div className="inline-flex items-center gap-1.5 bg-primary/10 text-primary rounded-full px-3 py-1 text-[10px] font-bold tracking-[0.2em] uppercase mb-3">
              <BarChart3 size={11} /> Reports Engine
            </div>
            <h1 className="text-3xl font-black tracking-tight text-foreground">Reports</h1>
            <p className="text-xs text-muted-foreground font-semibold mt-1">
              Generate, review, and export detailed financial reports from real transaction data
            </p>
          </div>
        </header>

        {/* ── Generation Control Bar ────────────────────────────────── */}
        <div className="bg-card/60 backdrop-blur-xl border border-border p-5 rounded-2xl shadow-sm space-y-4">
          <h2 className="text-xs font-black uppercase tracking-wider text-muted-foreground">Report Generator</h2>

          <div className="flex flex-wrap items-end gap-4">
            {/* Date Mode */}
            <div className="flex flex-col gap-1.5">
              <label className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground flex items-center gap-1">
                <Calendar size={10} /> Date Range
              </label>
              <select
                value={dateMode}
                onChange={(e) => setDateMode(e.target.value as any)}
                className="h-10 px-3 rounded-xl border border-border bg-background text-xs font-bold outline-none cursor-pointer focus:ring-2 focus:ring-primary/20"
              >
                <option value="today">Today</option>
                <option value="this-week">This Week</option>
                <option value="this-month">This Month</option>
                <option value="this-year">This Year</option>
                <option value="custom">Custom Range</option>
              </select>
            </div>

            {/* Custom date inputs */}
            <AnimatePresence>
              {dateMode === "custom" && (
                <motion.div
                  initial={{ opacity: 0, width: 0 }}
                  animate={{ opacity: 1, width: "auto" }}
                  exit={{ opacity: 0, width: 0 }}
                  className="flex items-end gap-2 overflow-hidden"
                >
                  <div className="flex flex-col gap-1.5">
                    <label className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground">From</label>
                    <input
                      type="date"
                      value={customStart}
                      onChange={(e) => setCustomStart(e.target.value)}
                      className="h-10 px-3 rounded-xl border border-border bg-background text-xs font-bold outline-none focus:ring-2 focus:ring-primary/20"
                    />
                  </div>
                  <div className="flex flex-col gap-1.5">
                    <label className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground">To</label>
                    <input
                      type="date"
                      value={customEnd}
                      onChange={(e) => setCustomEnd(e.target.value)}
                      className="h-10 px-3 rounded-xl border border-border bg-background text-xs font-bold outline-none focus:ring-2 focus:ring-primary/20"
                    />
                  </div>
                </motion.div>
              )}
            </AnimatePresence>

            {/* Report Category */}
            <div className="flex flex-col gap-1.5">
              <label className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground flex items-center gap-1">
                <Filter size={10} /> Category
              </label>
              <select
                value={reportType}
                onChange={(e) => setReportType(e.target.value as any)}
                className="h-10 px-3 rounded-xl border border-border bg-background text-xs font-bold outline-none cursor-pointer focus:ring-2 focus:ring-primary/20"
              >
                <option value="Sales">Sales Report</option>
                <option value="Inventory">Inventory Report</option>
                <option value="Financial">Financial Overview</option>
              </select>
            </div>

            <button
              disabled={loading || (dateMode === "custom" && (!customStart || !customEnd))}
              onClick={handleGenerateReport}
              className="h-10 px-6 rounded-xl btn-gradient text-white text-xs font-black shadow-lg shadow-primary/20 hover:shadow-primary/30 transition-all flex items-center gap-2 cursor-pointer disabled:opacity-50 mt-auto"
            >
              {loading ? <Loader2 size={14} className="animate-spin" /> : <Plus size={14} />}
              Generate Report
            </button>
          </div>
        </div>

        {/* ── Table Search & Type Filter Row ───────────────────────── */}
        <div className="bg-card/60 backdrop-blur-xl border border-border p-4 rounded-2xl shadow-sm flex flex-wrap items-center justify-between gap-4">
          <div className="flex flex-wrap items-center gap-3">
            <div className="flex items-center gap-2 bg-background border border-border rounded-xl px-3 h-10">
              <Filter size={14} className="text-muted-foreground" />
              <select
                value={typeFilter}
                onChange={(e) => setTypeFilter(e.target.value as any)}
                className="bg-transparent text-xs font-bold outline-none cursor-pointer"
              >
                <option value="all">All Types</option>
                <option value="Sales">Sales</option>
                <option value="Inventory">Inventory</option>
                <option value="Financial">Financial</option>
              </select>
            </div>

            <div className="relative w-48 group">
              <Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground group-focus-within:text-primary transition-colors" />
              <input
                type="text"
                value={search}
                onChange={(e) => setSearch(e.target.value)}
                placeholder="Search reports..."
                className="h-10 w-full pl-9 pr-3 rounded-xl border border-border bg-background outline-none text-xs font-medium focus:ring-2 focus:ring-primary/20 transition-all"
              />
            </div>
          </div>

          <span className="text-[10px] font-bold text-muted-foreground uppercase">
            {filteredReports.length} report{filteredReports.length !== 1 ? "s" : ""}
          </span>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-10 gap-6">

          {/* LEFT: Report Table (70%) */}
          <div className="lg:col-span-7 bg-card/60 backdrop-blur-xl border border-border rounded-3xl shadow-sm overflow-hidden flex flex-col">
            <div className="p-5 border-b border-border/50 flex items-center justify-between">
              <h2 className="text-sm font-black uppercase tracking-wider text-foreground">Generated Reports</h2>
            </div>

            <div className="overflow-x-auto flex-1">
              <table className="w-full text-left border-collapse whitespace-nowrap">
                <thead>
                  <tr className="bg-muted/10 border-b border-border/50 text-[10px] font-black uppercase tracking-wider text-muted-foreground">
                    <th className="py-4 px-6">Report Name</th>
                    <th className="py-4 px-6">Type</th>
                    <th className="py-4 px-6">Generated Date</th>
                    <th className="py-4 px-6">Created By</th>
                    <th className="py-4 px-6 text-right">Actions</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-border/50">
                  {paginatedReports.length === 0 ? (
                    <tr>
                      <td colSpan={5} className="py-16 text-center text-muted-foreground text-xs font-bold">
                        {loading ? (
                          <div className="flex items-center justify-center gap-2">
                            <Loader2 size={16} className="animate-spin" /> Generating report from real data…
                          </div>
                        ) : reports.length === 0 ? (
                          <div>
                            <p className="font-bold">No reports generated yet.</p>
                            <p className="text-muted-foreground/60 mt-1">Use the generator above to create your first report.</p>
                          </div>
                        ) : (
                          "No reports match your filters."
                        )}
                      </td>
                    </tr>
                  ) : (
                    paginatedReports.map((report) => (
                      <tr key={report.id} className="hover:bg-muted/5 transition-colors">
                        <td className="py-4 px-6 max-w-[220px]">
                          <div className="flex items-center gap-3">
                            <div className="w-8 h-8 rounded-lg bg-indigo-500/10 text-indigo-500 flex items-center justify-center shrink-0">
                              <FileText size={14} />
                            </div>
                            <div className="truncate">
                              <div className="font-bold text-sm text-foreground truncate">{report.name}</div>
                              <div className="text-[10px] text-muted-foreground truncate mt-0.5">{report.summary}</div>
                            </div>
                          </div>
                        </td>
                        <td className="py-4 px-6">
                          <HeroBadge
                            color={report.type === "Sales" ? "success" : report.type === "Financial" ? "default" : "default"}
                            variant="soft"
                            size="sm"
                            className="uppercase font-black tracking-wider text-[9px]"
                          >
                            {report.type}
                          </HeroBadge>
                        </td>
                        <td className="py-4 px-6 font-medium text-xs text-muted-foreground">
                          {new Date(report.createdAt).toLocaleDateString()}
                        </td>
                        <td className="py-4 px-6 text-xs font-bold text-foreground">{report.generatedBy}</td>
                        <td className="py-4 px-6 text-right">
                          <div className="flex items-center justify-end gap-2">
                            <button
                              onClick={() => printReport(report)}
                              className="p-2 bg-indigo-500/10 text-indigo-500 hover:bg-indigo-500/20 rounded-lg transition-colors cursor-pointer"
                              title="Download / Print PDF"
                            >
                              <Printer size={14} />
                            </button>
                            <button
                              onClick={() => exportCSV(report)}
                              className="p-2 bg-emerald-500/10 text-emerald-500 hover:bg-emerald-500/20 rounded-lg transition-colors cursor-pointer"
                              title="Export CSV"
                            >
                              <FileSpreadsheet size={14} />
                            </button>
                            <button
                              onClick={() => handleDeleteReport(report.id, report.name)}
                              className="p-2 bg-rose-500/10 text-rose-500 hover:bg-rose-500/20 rounded-lg transition-colors cursor-pointer"
                              title="Delete"
                            >
                              <Trash2 size={14} />
                            </button>
                          </div>
                        </td>
                      </tr>
                    ))
                  )}
                </tbody>
              </table>
            </div>

            {/* Pagination */}
            {totalPages > 1 && (
              <div className="p-4 border-t border-border/50 flex justify-between items-center bg-muted/5">
                <span className="text-[10px] font-bold text-muted-foreground uppercase">
                  Page {currentPage} of {totalPages}
                </span>
                <div className="flex gap-2">
                  <button
                    disabled={currentPage === 1}
                    onClick={() => setCurrentPage((p) => Math.max(1, p - 1))}
                    className="p-1.5 border border-border rounded-lg disabled:opacity-30 hover:bg-muted/10 cursor-pointer transition-colors"
                  >
                    <ChevronLeft size={14} />
                  </button>
                  <button
                    disabled={currentPage === totalPages}
                    onClick={() => setCurrentPage((p) => Math.min(totalPages, p + 1))}
                    className="p-1.5 border border-border rounded-lg disabled:opacity-30 hover:bg-muted/10 cursor-pointer transition-colors"
                  >
                    <ChevronRight size={14} />
                  </button>
                </div>
              </div>
            )}
          </div>

          {/* RIGHT: Financial Sidebar (30%) */}
          <div className="lg:col-span-3 space-y-6">

            {/* Financial Summary */}
            <div className="bg-card/60 backdrop-blur-xl border border-border rounded-3xl p-6 shadow-sm">
              <div className="flex items-center justify-between mb-4">
                <h3 className="text-xs font-black uppercase tracking-wider text-muted-foreground flex items-center gap-2">
                  <DollarSign size={12} /> Financial Summary
                </h3>
                {DEMO_MODE && (
                  <span className="text-[9px] font-black uppercase tracking-wider bg-amber-500/10 text-amber-600 px-2 py-0.5 rounded-full">
                    Demo
                  </span>
                )}
              </div>

              {/* Donut Chart */}
              <div className="h-44 w-full">
                <ResponsiveContainer width="100%" height="100%">
                  <PieChart>
                    <Pie
                      data={donutData}
                      innerRadius={48}
                      outerRadius={66}
                      paddingAngle={4}
                      dataKey="value"
                      stroke="none"
                    >
                      {donutData.map((entry, index) => (
                        <Cell key={`cell-${index}`} fill={entry.color} />
                      ))}
                    </Pie>
                    <Tooltip
                      formatter={(value: any) =>
                        activeStats && (activeStats.revenue > 0 || activeStats.expenses > 0)
                          ? `${Number(value).toLocaleString("en-US", { minimumFractionDigits: 2 })} DH`
                          : "No data yet"
                      }
                      contentStyle={{ borderRadius: "12px", border: "none", boxShadow: "0 10px 25px -5px rgba(0,0,0,0.1)" }}
                    />
                    <Legend verticalAlign="bottom" height={32} iconType="circle" wrapperStyle={{ fontSize: "10px", fontWeight: "bold" }} />
                  </PieChart>
                </ResponsiveContainer>
              </div>

              {/* Metric rows */}
              <div className="mt-4 space-y-3 border-t border-border/50 pt-4">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <span className="w-2.5 h-2.5 rounded-full bg-emerald-500 shrink-0" />
                    <span className="text-xs font-bold text-muted-foreground">Revenue</span>
                  </div>
                  <span className="text-sm font-black text-emerald-500">
                    {activeStats && activeStats.revenue > 0
                      ? activeStats.revenue.toLocaleString("en-US", { minimumFractionDigits: 2 }) + " DH"
                      : "—"}
                  </span>
                </div>

                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <span className="w-2.5 h-2.5 rounded-full bg-rose-500 shrink-0" />
                    <span className="text-xs font-bold text-muted-foreground">Expenses</span>
                  </div>
                  <span className="text-sm font-black text-rose-500">
                    {activeStats && activeStats.expenses > 0
                      ? activeStats.expenses.toLocaleString("en-US", { minimumFractionDigits: 2 }) + " DH"
                      : "—"}
                  </span>
                </div>

                <div className="flex items-center justify-between border-t border-border/50 pt-3">
                  <div className="flex items-center gap-2">
                    <span className="w-2.5 h-2.5 rounded-full bg-indigo-500 shrink-0" />
                    <span className="text-xs font-black text-foreground">Net Profit (Est.)</span>
                  </div>
                  <span className="text-base font-black text-foreground">
                    {activeStats && activeStats.revenue > 0
                      ? netProfit.toLocaleString("en-US", { minimumFractionDigits: 2 }) + " DH"
                      : "—"}
                  </span>
                </div>
              </div>
            </div>

            {/* Ask Emexa AI */}
            <div className="bg-gradient-to-br from-indigo-500/10 to-purple-500/10 border border-indigo-500/20 rounded-3xl p-6 shadow-sm relative overflow-hidden">
              <div className="absolute -right-4 -top-4 w-24 h-24 bg-indigo-500/20 rounded-full blur-xl pointer-events-none" />
              <div className="flex items-center gap-3 mb-4 relative z-10">
                <div className="w-10 h-10 rounded-2xl bg-indigo-500 text-white flex items-center justify-center shadow-lg shadow-indigo-500/30 shrink-0">
                  <Sparkles size={18} />
                </div>
                <div>
                  <h3 className="font-black text-sm text-foreground">Ask Emexa</h3>
                  <p className="text-[10px] text-muted-foreground uppercase tracking-wider font-bold">AI Assistant</p>
                </div>
              </div>
              <p className="text-xs font-medium text-muted-foreground mb-4 leading-relaxed relative z-10">
                "I can help you analyze these reports, find anomalies, or suggest cost-cutting measures. What would you like to know?"
              </p>
              <div className="relative z-10">
                <input
                  type="text"
                  placeholder="Ask something..."
                  className="w-full h-10 pl-3 pr-10 rounded-xl bg-background/50 border border-border/50 text-xs font-medium outline-none focus:ring-2 focus:ring-indigo-500/20 transition-all"
                />
                <button className="absolute right-1 top-1 w-8 h-8 rounded-lg bg-indigo-500 text-white flex items-center justify-center hover:bg-indigo-600 transition-colors cursor-pointer">
                  <ChevronRight size={16} />
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Toast */}
      <AnimatePresence>
        {toast && (
          <motion.div
            initial={{ opacity: 0, y: 50, x: "-50%" }}
            animate={{ opacity: 1, y: 0, x: "-50%" }}
            exit={{ opacity: 0, y: 20, x: "-50%" }}
            className={`fixed bottom-6 left-1/2 z-[9999] px-6 py-3 rounded-xl shadow-2xl text-xs font-black uppercase tracking-wider flex items-center gap-2 border ${
              toast.type === "success"
                ? "bg-emerald-600 text-white border-emerald-500"
                : toast.type === "error"
                ? "bg-rose-600 text-white border-rose-500"
                : "bg-slate-800 text-white border-slate-700"
            }`}
          >
            {toast.type === "success" && <CheckCircle2 size={14} className="text-emerald-200" />}
            {toast.type === "error" && <AlertCircle size={14} className="text-rose-200" />}
            {toast.message}
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}